Simplifiquei partes do texto e corrigi alguns erros oritgráficos
ilhas-maldivas/como-sair-de-angola pull request #7
Opened 2022-02-08 11:08 UTC by e200

2022-02-09 07:43 UTC, pedromassango requested changes

2022-02-09 07:43 UTC, pedromassango commented on readme.md
> +Antes de sair do país, você precisa ter um objectivo e um plano para alcançá-lo. Procure não cometer o erro de muitos que saiem de cabeça sem planejamento.
substituir "saiem" para "saem"

2022-02-09 07:43 UTC, pedromassango commented on readme.md
> +Faça uma investigação sobre os possíveis países onde gostaria de viver, compare as vantagens e desvantagens, leve o tempo que precisar para entender os prós e contra de cada um e assim que encontrar
```suggestion
Faça uma investigação sobre os possíveis países onde gostaria de viver, compare as vantagens e desvantagens, leve o tempo que precisar para entender os prós e contra de cada um, e assim que encontrar o país que mais se adequa ao seus objetivos, comece a correr atrás dos requisitos para viver legalmente nesse país!
```

2022-02-09 07:43 UTC, pedromassango commented on readme.md
> +Com base na experiência de várias pessoas, criamos esta lista com links onde poderá encontrar conteúdo útil específico ao processo de emigração dos países listados. Se você já passou por um processo
```suggestion
Com base na experiência de várias pessoas, criamos esta lista com links onde poderá encontrar conteúdo útil específico ao processo de emigração dos países listados. Se você já passou por um processo de emigração e gostaria de contribuir na nossa lista de países, um **Pull Request** seu será muito bem-vindo.
```

2022-02-09 07:43 UTC, pedromassango commented on readme.md
> +Abaixo segue a lista de países com conteúdo
```suggestion
Abaixo segue a lista de países com o seu devido conteúdo informativo 
```

2022-02-10 06:43 UTC, pedromassango approved these changes
LGTM

2022-02-10 10:30 UTC, e200 commented
> LGTM

What it means?

2022-02-10 10:30 UTC, merged

2022-02-10 17:21 UTC, pedromassango commented
> What it means?

Look Good To Me